### PR TITLE
MR-1136 Dynamic default zoom and map centering

### PR DESCRIPTION
**Pull request by vercasson**
- [x] This change is documented in CHANGELOG.md

### CODE REVIEW

**Comment by vercasson** [comment]
Isn't working all of sudden after doing some cleanup

**Comment by vercasson** [comment]
> Isn't working all of sudden after doing some cleanup

All good. Branch was stale, had to pull master. Didn't have the updated mock floor data. Phewww.

**Review by wavebeem — APPROVED** [review]
Why is it 0.7 now instead of 0.5? Looks good tho

**Comment by vercasson** [comment]
> Why is it 0.7 now instead of 0.5? Looks good tho

@wavebeem `0.7` gives a tiny bit more room (less whitespace around map)

**Pull request merged**
