### PR TITLE
MRC-1606 Analytics, GA4 migration

### PR DESCRIPTION
**Pull request by amyhliao**
- [x] This change is documented in CHANGELOG.md

image

### CODE REVIEW

**Comment by amyhliao** [comment]
The build is failing due to the fact I created a new file to hold the GA4 API key which is not present in prod build.

**Comment by vercasson** [comment]
> The build is failing due to the fact I created a new file to hold the GA4 API key which is not present in prod build. Hopefully, this will not be a major issue when the file is present in prod. @vercasson @tarakreft can you possibly confirm this in case it might break future builds?

@amyhliao What line in Travis are you seeing that mentions a fail due to a new file?

**Comment by amyhliao** [comment]
@vercasson I found the error here:
image

**Comment by vercasson** [comment]
> @vercasson I found the error here: image

This is because you're importing a file thats not part of the project (and never will be based on the change you made in `.gitignore`). Modules you wish to import need to be part of the project.

**Comment by amyhliao** [comment]
@vercasson thanks for clarifying. I will need to update this then

**Review by tarakreft — APPROVED** [review]

**Review by vercasson — APPROVED** [review]

**Pull request merged**
